spring.application.name=healthBot

twilio.accountSid=AC478e58366e1cde2df92da83490bcbc35
twilio.authToken=d41664f571453f93589fe46d71d54d3f
twilio.whatsappNumber=whatsapp:+14155238886

spring.datasource.url=jdbc:mysql://localhost:3306/health_chatbot_db
spring.datasource.username=root
spring.datasource.password=aadilofficial111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=ERROR
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

